use super::types::{
    ArenaLeagueView, ArenaRatingMethodology, ArenaRatingRanking, ArenaRatingsResponse,
    ArenaSeasonRatingView,
};
use serde::Deserialize;
use std::collections::HashSet;
use std::fs::File;
use std::io::Read;
use std::path::{Path, PathBuf};
use tracing::warn;

const DEFAULT_ARENA_RATINGS_PATH: &str = "data/arena_ratings.json";
const MAX_ARENA_RATINGS_BYTES: u64 = 2 * 1024 * 1024;
const MAX_ARENA_SEASON_ROSTER: usize = 1_000;
const MAX_ARENA_RATING_SOURCE_BYTES: usize = 50 * 1024;
const MAX_ARENA_RATING_WASM_BYTES: usize = 2 * 1024 * 1024;
const MAX_RATING: f64 = 100.0;

#[derive(Debug, Deserialize)]
struct ArenaRatingsSnapshot {
    schema_version: u32,
    active: bool,
    season_id: String,
    generated_at: String,
    ranking: ArenaRatingRanking,
    methodology: ArenaRatingMethodology,
    #[serde(default)]
    league: Option<ArenaLeagueView>,
    roster: Vec<ArenaSeasonRatingView>,
}

pub(crate) fn ratings_path_from_env() -> PathBuf {
    std::env::var("MGS_ARENA_RATINGS_PATH")
        .ok()
        .map(|raw| raw.trim().to_owned())
        .filter(|raw| !raw.is_empty())
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(DEFAULT_ARENA_RATINGS_PATH))
}

pub(crate) fn load_ratings_response(path: &Path) -> ArenaRatingsResponse {
    match read_ratings_snapshot(path).and_then(validate_ratings_snapshot) {
        Ok(snapshot) => ArenaRatingsResponse {
            schema_version: snapshot.schema_version,
            active: true,
            status: "active".to_owned(),
            season_id: Some(snapshot.season_id),
            generated_at: Some(snapshot.generated_at),
            ranking: Some(snapshot.ranking),
            methodology: Some(snapshot.methodology),
            league: snapshot.league,
            roster: snapshot.roster,
        },
        Err(SnapshotError::Missing) => ArenaRatingsResponse::no_active_season(),
        Err(err) => {
            // The artifact is generated by a separate season process. A partial
            // write or invalid artifact must never turn a public telemetry read
            // into a server error or leak a local filesystem path to clients.
            warn!(reason = err.log_reason(), "Arena ratings snapshot ignored");
            ArenaRatingsResponse::no_active_season()
        }
    }
}

#[derive(Debug)]
enum SnapshotError {
    Missing,
    Io,
    TooLarge,
    InvalidJson,
    InvalidData(&'static str),
}

impl SnapshotError {
    fn log_reason(&self) -> &'static str {
        match self {
            Self::Missing => "missing",
            Self::Io => "io_error",
            Self::TooLarge => "too_large",
            Self::InvalidJson => "invalid_json",
            Self::InvalidData(reason) => reason,
        }
    }
}

fn read_ratings_snapshot(path: &Path) -> Result<ArenaRatingsSnapshot, SnapshotError> {
    let file = match File::open(path) {
        Ok(file) => file,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => {
            return Err(SnapshotError::Missing)
        }
        Err(_) => return Err(SnapshotError::Io),
    };

    let mut bytes = Vec::new();
    file.take(MAX_ARENA_RATINGS_BYTES + 1)
        .read_to_end(&mut bytes)
        .map_err(|_| SnapshotError::Io)?;
    if bytes.len() as u64 > MAX_ARENA_RATINGS_BYTES {
        return Err(SnapshotError::TooLarge);
    }

    serde_json::from_slice(&bytes).map_err(|_| SnapshotError::InvalidJson)
}

fn validate_ratings_snapshot(
    mut snapshot: ArenaRatingsSnapshot,
) -> Result<ArenaRatingsSnapshot, SnapshotError> {
    if snapshot.schema_version != 1 {
        return Err(SnapshotError::InvalidData("unsupported_schema_version"));
    }
    if !snapshot.active {
        return Err(SnapshotError::Missing);
    }

    snapshot.season_id = snapshot.season_id.trim().to_owned();
    if snapshot.season_id.is_empty()
        || snapshot.season_id.len() > 128
        || !snapshot
            .season_id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || b"-_.:".contains(&byte))
    {
        return Err(SnapshotError::InvalidData("invalid_season_id"));
    }

    validate_timestamp(&mut snapshot.generated_at, "invalid_generated_at")?;
    validate_ranking(&mut snapshot.ranking)?;

    validate_methodology(&mut snapshot.methodology)?;
    if let Some(league) = &mut snapshot.league {
        validate_league(league, snapshot.roster.len())?;
    }

    if snapshot.roster.is_empty() || snapshot.roster.len() > MAX_ARENA_SEASON_ROSTER {
        return Err(SnapshotError::InvalidData("invalid_roster_size"));
    }

    let roster_len = snapshot.roster.len();
    let mut ranks = HashSet::with_capacity(roster_len);
    let mut provider_ranks = HashSet::with_capacity(roster_len);
    let mut model_ids = HashSet::with_capacity(roster_len);
    let mut provider_models = HashSet::with_capacity(roster_len);
    for entry in &mut snapshot.roster {
        if entry.rank == 0 || !ranks.insert(entry.rank) {
            return Err(SnapshotError::InvalidData("invalid_rank"));
        }
        if entry.provider_rank == 0 || !provider_ranks.insert(entry.provider_rank) {
            return Err(SnapshotError::InvalidData("invalid_provider_rank"));
        }

        trim_and_validate_label(&mut entry.model_id, 256, "invalid_model_id")?;
        trim_and_validate_label(&mut entry.model_name, 256, "invalid_model_name")?;
        trim_and_validate_label(&mut entry.provider_model, 256, "invalid_provider_model")?;
        if !model_ids.insert(entry.model_id.clone()) {
            return Err(SnapshotError::InvalidData("duplicate_model_id"));
        }
        if !provider_models.insert(entry.provider_model.clone()) {
            return Err(SnapshotError::InvalidData("duplicate_provider_model"));
        }
        if let Some(slug) = &mut entry.canonical_slug {
            trim_and_validate_label(slug, 256, "invalid_canonical_slug")?;
        }

        for rating in [
            entry.personal_rating,
            entry.team_rating,
            entry.collaboration_rating,
            entry.overall_rating,
            entry.world_rating,
            entry.strategy_rating,
        ] {
            if !rating.is_finite() || !(0.0..=MAX_RATING).contains(&rating) {
                return Err(SnapshotError::InvalidData("invalid_rating"));
            }
        }
        let expected_overall = entry.personal_rating * snapshot.methodology.personal_weight
            + entry.team_rating * snapshot.methodology.team_weight
            + entry.collaboration_rating * snapshot.methodology.collaboration_weight;
        if (entry.overall_rating - expected_overall).abs() > 0.05 {
            return Err(SnapshotError::InvalidData("inconsistent_overall_rating"));
        }
        if snapshot.methodology.world_strategy_weight > 0.0 {
            let expected_strategy = entry.overall_rating
                * snapshot.methodology.duel_strategy_weight
                + entry.world_rating * snapshot.methodology.world_strategy_weight;
            if (entry.strategy_rating - expected_strategy).abs() > 0.05 {
                return Err(SnapshotError::InvalidData("inconsistent_strategy_rating"));
            }
        } else if entry.strategy_rating != 0.0
            && (entry.strategy_rating - entry.overall_rating).abs() > 0.05
        {
            return Err(SnapshotError::InvalidData("inconsistent_strategy_rating"));
        }

        if entry.source_limit_bytes == 0
            || entry.source_limit_bytes > MAX_ARENA_RATING_SOURCE_BYTES
            || entry.source_limit_bytes != snapshot.methodology.source_limit_bytes
            || entry.source_bytes > entry.source_limit_bytes
        {
            return Err(SnapshotError::InvalidData("invalid_source_size"));
        }
        let Some(hash) = &mut entry.source_sha256 else {
            return Err(SnapshotError::InvalidData("missing_source_sha256"));
        };
        *hash = hash.trim().to_ascii_lowercase();
        if !is_sha256(hash) {
            return Err(SnapshotError::InvalidData("invalid_source_sha256"));
        }
        if !entry.compiled || entry.simulated {
            return Err(SnapshotError::InvalidData("unverified_fighter"));
        }
        if !matches!(entry.wasm_bytes, Some(bytes) if bytes > 0 && bytes <= MAX_ARENA_RATING_WASM_BYTES)
        {
            return Err(SnapshotError::InvalidData("invalid_wasm_size"));
        }
        if let Some(hash) = entry.wasm_sha256.as_deref() {
            if !is_lowercase_sha256(hash) {
                return Err(SnapshotError::InvalidData("invalid_wasm_sha256"));
            }
        }
        if !matches!(entry.compile_attempts, Some(1..=100)) {
            return Err(SnapshotError::InvalidData("invalid_compile_attempts"));
        }
        if entry
            .wins
            .saturating_add(entry.losses)
            .saturating_add(entry.draws)
            != entry.matches_played
        {
            return Err(SnapshotError::InvalidData("invalid_match_record"));
        }
        if entry.matches_played == 0 || entry.evaluation_engagements < entry.matches_played {
            return Err(SnapshotError::InvalidData("invalid_evaluation_engagements"));
        }
        if let Some(league) = &snapshot.league {
            if entry.epochs_played != league.epochs_completed
                || entry.epoch_wins > entry.epochs_played
                || !matches!(entry.best_epoch_rank, Some(rank) if (1..=roster_len).contains(&rank))
                || !matches!(entry.last_epoch_rank, Some(rank) if (1..=roster_len).contains(&rank))
                || entry.season_points
                    > league
                        .points_by_rank
                        .iter()
                        .copied()
                        .max()
                        .unwrap_or(0)
                        .saturating_mul(entry.epochs_played)
            {
                return Err(SnapshotError::InvalidData("invalid_league_record"));
            }
        }
        let Some(status) = &mut entry.integrity_status else {
            return Err(SnapshotError::InvalidData("missing_integrity_status"));
        };
        trim_and_validate_label(status, 64, "invalid_integrity_status")?;
        if status != "verified_wasm" {
            return Err(SnapshotError::InvalidData("unverified_integrity_status"));
        }
    }

    snapshot.roster.sort_by_key(|entry| entry.rank);
    if snapshot
        .roster
        .iter()
        .enumerate()
        .any(|(index, entry)| entry.rank != index + 1)
    {
        return Err(SnapshotError::InvalidData("non_contiguous_ranks"));
    }
    if snapshot.league.is_some()
        && snapshot.roster.windows(2).any(|pair| {
            let left = &pair[0];
            let right = &pair[1];
            left.season_points < right.season_points
                || (left.season_points == right.season_points && left.epoch_wins < right.epoch_wins)
                || (left.season_points == right.season_points
                    && left.epoch_wins == right.epoch_wins
                    && left.strategy_rating < right.strategy_rating)
        })
    {
        return Err(SnapshotError::InvalidData("invalid_league_order"));
    }

    Ok(snapshot)
}

fn validate_league(league: &mut ArenaLeagueView, roster_size: usize) -> Result<(), SnapshotError> {
    trim_and_validate_label(&mut league.format, 64, "invalid_league_format")?;
    trim_and_validate_label(&mut league.week_id, 16, "invalid_league_week")?;
    if !is_iso_week_id(&league.week_id) {
        return Err(SnapshotError::InvalidData("invalid_league_week"));
    }
    validate_timestamp(&mut league.frozen_at, "invalid_league_frozen_at")?;
    if league.epochs_completed == 0
        || league.total_seed_count == 0
        || league.points_by_rank.len() != roster_size
        || league
            .points_by_rank
            .iter()
            .any(|points| *points > 1_000_000)
        || league
            .points_by_rank
            .windows(2)
            .any(|pair| pair[0] < pair[1])
    {
        return Err(SnapshotError::InvalidData("invalid_league_points"));
    }
    if league.standings_order != ["season_points", "epoch_wins", "strategy_rating"] {
        return Err(SnapshotError::InvalidData("invalid_standings_order"));
    }
    league.ledger_sha256 = league.ledger_sha256.trim().to_ascii_lowercase();
    if !is_sha256(&league.ledger_sha256) {
        return Err(SnapshotError::InvalidData("invalid_league_ledger"));
    }
    if league.recent_epochs.len() > 64 {
        return Err(SnapshotError::InvalidData("too_many_recent_epochs"));
    }
    for epoch in &mut league.recent_epochs {
        trim_and_validate_label(&mut epoch.epoch_id, 64, "invalid_epoch_id")?;
        validate_timestamp(&mut epoch.completed_at, "invalid_epoch_timestamp")?;
        epoch.artifact_sha256 = epoch.artifact_sha256.trim().to_ascii_lowercase();
        if epoch.index >= league.epochs_completed
            || epoch.seeds.is_empty()
            || epoch.seeds.len() > 256
            || epoch.battle_requests == 0
            || epoch.total_engagements == 0
            || !is_sha256(&epoch.artifact_sha256)
            || epoch.standings.len() != roster_size
        {
            return Err(SnapshotError::InvalidData("invalid_recent_epoch"));
        }
        let mut epoch_ranks = HashSet::with_capacity(roster_size);
        let mut epoch_models = HashSet::with_capacity(roster_size);
        for standing in &mut epoch.standings {
            trim_and_validate_label(&mut standing.model_id, 256, "invalid_epoch_model")?;
            if !(1..=roster_size).contains(&standing.epoch_rank)
                || !epoch_ranks.insert(standing.epoch_rank)
                || !epoch_models.insert(standing.model_id.clone())
                || !standing.overall_rating.is_finite()
                || !(0.0..=MAX_RATING).contains(&standing.overall_rating)
                || !standing.world_rating.is_finite()
                || !(0.0..=MAX_RATING).contains(&standing.world_rating)
                || !standing.strategy_rating.is_finite()
                || !(0.0..=MAX_RATING).contains(&standing.strategy_rating)
                || standing.points_awarded != league.points_by_rank[standing.epoch_rank - 1]
            {
                return Err(SnapshotError::InvalidData("invalid_epoch_standing"));
            }
        }
    }
    Ok(())
}

fn is_iso_week_id(value: &str) -> bool {
    let bytes = value.as_bytes();
    if bytes.len() != 8
        || bytes[4] != b'-'
        || bytes[5] != b'W'
        || !bytes[..4].iter().all(u8::is_ascii_digit)
        || !bytes[6..].iter().all(u8::is_ascii_digit)
    {
        return false;
    }
    matches!(value[6..].parse::<u8>(), Ok(1..=53))
}

fn validate_methodology(methodology: &mut ArenaRatingMethodology) -> Result<(), SnapshotError> {
    methodology.prompt_sha256 = methodology.prompt_sha256.trim().to_ascii_lowercase();
    if !is_sha256(&methodology.prompt_sha256) {
        return Err(SnapshotError::InvalidData("invalid_prompt_sha256"));
    }
    if methodology.source_limit_bytes == 0
        || methodology.source_limit_bytes > MAX_ARENA_RATING_SOURCE_BYTES
    {
        return Err(SnapshotError::InvalidData("invalid_source_limit"));
    }
    if methodology.modes.is_empty() || methodology.modes.len() > 16 {
        return Err(SnapshotError::InvalidData("invalid_modes"));
    }
    let mut modes = HashSet::with_capacity(methodology.modes.len());
    for mode in &mut methodology.modes {
        trim_and_validate_label(mode, 64, "invalid_mode")?;
        if !modes.insert(mode.clone()) {
            return Err(SnapshotError::InvalidData("duplicate_mode"));
        }
    }
    if methodology.seed_sets.is_empty() || methodology.seed_sets.len() > 10_000 {
        return Err(SnapshotError::InvalidData("invalid_seed_sets"));
    }
    let unique_seeds: HashSet<u64> = methodology.seed_sets.iter().copied().collect();
    if unique_seeds.len() != methodology.seed_sets.len() {
        return Err(SnapshotError::InvalidData("duplicate_seed"));
    }
    if !(1..=100).contains(&methodology.team_size) {
        return Err(SnapshotError::InvalidData("invalid_team_size"));
    }
    if !(1..=10_000).contains(&methodology.rounds) {
        return Err(SnapshotError::InvalidData("invalid_rounds"));
    }

    let weights = [
        methodology.personal_weight,
        methodology.team_weight,
        methodology.collaboration_weight,
    ];
    if weights
        .iter()
        .any(|weight| !weight.is_finite() || !(0.0..=1.0).contains(weight))
        || (weights.iter().sum::<f64>() - 1.0).abs() > 0.001
    {
        return Err(SnapshotError::InvalidData("invalid_rating_weights"));
    }

    let strategy_weights = [
        methodology.duel_strategy_weight,
        methodology.world_strategy_weight,
    ];
    if strategy_weights
        .iter()
        .any(|weight| !weight.is_finite() || !(0.0..=1.0).contains(weight))
        || (strategy_weights.iter().sum::<f64>() - 1.0).abs() > 0.001
    {
        return Err(SnapshotError::InvalidData("invalid_strategy_weights"));
    }
    if methodology.world_strategy_weight > 0.0
        && (!(1..=5).contains(&methodology.world_squad_size)
            || !(1..=2_000).contains(&methodology.world_max_ticks))
    {
        return Err(SnapshotError::InvalidData("invalid_world_methodology"));
    }

    trim_and_validate_label(
        &mut methodology.collaboration_kind,
        128,
        "invalid_collaboration_kind",
    )?;
    if methodology.notes.len() > 16
        || methodology
            .notes
            .iter_mut()
            .any(|note| trim_and_validate_label(note, 512, "invalid_note").is_err())
    {
        return Err(SnapshotError::InvalidData("invalid_notes"));
    }

    Ok(())
}

fn validate_ranking(ranking: &mut ArenaRatingRanking) -> Result<(), SnapshotError> {
    trim_and_validate_label(&mut ranking.source, 512, "invalid_ranking_source")?;
    trim_and_validate_label(&mut ranking.window, 64, "invalid_ranking_window")?;
    validate_timestamp(&mut ranking.retrieved_at, "invalid_ranking_retrieved_at")
}

fn validate_timestamp(value: &mut String, reason: &'static str) -> Result<(), SnapshotError> {
    trim_and_validate_label(value, 64, reason)?;
    // This is deliberately a light RFC3339 shape check. Parsing is left to
    // consumers, but arbitrary labels cannot masquerade as timestamps.
    let Some((_, time_and_zone)) = value.split_once('T') else {
        return Err(SnapshotError::InvalidData(reason));
    };
    let has_offset = time_and_zone
        .char_indices()
        .any(|(index, character)| index >= 8 && matches!(character, '+' | '-'));
    if !value.ends_with('Z') && !has_offset {
        return Err(SnapshotError::InvalidData(reason));
    }
    Ok(())
}

fn trim_and_validate_label(
    value: &mut String,
    max_len: usize,
    reason: &'static str,
) -> Result<(), SnapshotError> {
    *value = value.trim().to_owned();
    if value.is_empty() || value.len() > max_len || value.chars().any(char::is_control) {
        return Err(SnapshotError::InvalidData(reason));
    }
    Ok(())
}

fn is_sha256(value: &str) -> bool {
    value.len() == 64 && value.bytes().all(|byte| byte.is_ascii_hexdigit())
}

fn is_lowercase_sha256(value: &str) -> bool {
    value.len() == 64
        && value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use uuid::Uuid;

    fn temp_snapshot_path(label: &str) -> PathBuf {
        std::env::temp_dir().join(format!(
            "mgs-arena-ratings-{}-{}.json",
            label,
            Uuid::new_v4().simple()
        ))
    }

    fn valid_snapshot_json() -> String {
        serde_json::json!({
            "schema_version": 1,
            "active": true,
            "season_id": "weekly-2026-07-23",
            "generated_at": "2026-07-23T12:00:00Z",
            "ranking": {
                "source": "https://openrouter.ai/api/v1/models?sort=top-weekly",
                "window": "top-weekly",
                "retrieved_at": "2026-07-23T11:55:00Z"
            },
            "methodology": {
                "prompt_sha256": "a".repeat(64),
                "source_limit_bytes": 51200,
                "modes": ["arena", "ctf", "koth", "tdm"],
                "seed_sets": [1001, 2002, 3003, 4004],
                "team_size": 10,
                "rounds": 4,
                "personal_weight": 0.4,
                "team_weight": 0.35,
                "collaboration_weight": 0.25,
                "collaboration_kind": "team_context_v2"
            },
            "roster": [{
                "rank": 1,
                "provider_rank": 1,
                "model_id": "model_one",
                "model_name": "Model One",
                "provider_model": "provider/model-one",
                "personal_rating": 92.5,
                "team_rating": 88.0,
                "collaboration_rating": 84.25,
                "overall_rating": 88.86,
                "source_bytes": 2048,
                "source_limit_bytes": 51200,
                "source_sha256": "b".repeat(64),
                "compiled": true,
                "wasm_bytes": 4096,
                "wasm_sha256": "c".repeat(64),
                "compile_attempts": 1,
                "simulated": false,
                "wins": 7,
                "losses": 2,
                "draws": 1,
                "matches_played": 10,
                "evaluation_engagements": 100,
                "integrity_status": "verified_wasm"
            }]
        })
        .to_string()
    }

    #[test]
    fn valid_snapshot_is_loaded_and_normalized() {
        let path = temp_snapshot_path("valid");
        fs::write(&path, valid_snapshot_json()).expect("write snapshot");

        let response = load_ratings_response(&path);

        assert!(response.active);
        assert_eq!(response.status, "active");
        assert_eq!(response.season_id.as_deref(), Some("weekly-2026-07-23"));
        assert_eq!(response.roster.len(), 1);
        assert_eq!(response.roster[0].provider_model, "provider/model-one");
        assert_eq!(response.roster[0].overall_rating, 88.86);
        assert_eq!(
            response.roster[0].wasm_sha256.as_deref(),
            Some("cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc")
        );
        let _ = fs::remove_file(path);
    }

    #[test]
    fn legacy_snapshot_without_wasm_digest_remains_readable() {
        let path = temp_snapshot_path("legacy-no-wasm-digest");
        let mut fixture: serde_json::Value =
            serde_json::from_str(&valid_snapshot_json()).expect("valid fixture");
        fixture["roster"][0]
            .as_object_mut()
            .expect("roster entry")
            .remove("wasm_sha256");
        fs::write(&path, fixture.to_string()).expect("write legacy snapshot");

        let response = load_ratings_response(&path);

        assert!(response.active);
        assert!(response.roster[0].wasm_sha256.is_none());
        let _ = fs::remove_file(path);
    }

    #[test]
    fn present_wasm_digest_must_be_canonical_lowercase_sha256() {
        for invalid in [
            "C".repeat(64),
            "c".repeat(63),
            format!("{}g", "c".repeat(63)),
        ] {
            let path = temp_snapshot_path("invalid-wasm-digest");
            let mut fixture: serde_json::Value =
                serde_json::from_str(&valid_snapshot_json()).expect("valid fixture");
            fixture["roster"][0]["wasm_sha256"] = serde_json::json!(invalid);
            fs::write(&path, fixture.to_string()).expect("write invalid snapshot");

            let response = load_ratings_response(&path);
            assert!(!response.active);
            assert!(response.roster.is_empty());
            let _ = fs::remove_file(path);
        }
    }

    #[test]
    fn published_wasm_size_is_hard_capped() {
        let path = temp_snapshot_path("oversized-wasm");
        let mut fixture: serde_json::Value =
            serde_json::from_str(&valid_snapshot_json()).expect("valid fixture");
        fixture["roster"][0]["wasm_bytes"] = serde_json::json!(MAX_ARENA_RATING_WASM_BYTES + 1);
        fs::write(&path, fixture.to_string()).expect("write oversized snapshot");

        let response = load_ratings_response(&path);
        assert!(!response.active);
        assert!(response.roster.is_empty());
        let _ = fs::remove_file(path);
    }

    #[test]
    fn missing_snapshot_returns_no_active_season() {
        let response = load_ratings_response(&temp_snapshot_path("missing"));

        assert!(!response.active);
        assert_eq!(response.status, "no_active_season");
        assert!(response.season_id.is_none());
        assert!(response.roster.is_empty());
    }

    #[test]
    fn weekly_league_points_and_epoch_ledger_are_exposed() {
        let path = temp_snapshot_path("weekly");
        let mut fixture: serde_json::Value =
            serde_json::from_str(&valid_snapshot_json()).expect("valid fixture");
        fixture["league"] = serde_json::json!({
            "format": "weekly_continuous_v1",
            "week_id": "2026-W30",
            "frozen_at": "2026-07-20T00:00:00Z",
            "epochs_completed": 1,
            "total_seed_count": 4,
            "points_by_rank": [1000],
            "standings_order": ["season_points", "epoch_wins", "strategy_rating"],
            "ledger_sha256": "c".repeat(64),
            "recent_epochs": [{
                "index": 0,
                "epoch_id": "2026-W30-E000001",
                "completed_at": "2026-07-23T12:00:00Z",
                "seeds": [1, 2, 3, 4],
                "battle_requests": 1440,
                "total_engagements": 11160,
                "artifact_sha256": "d".repeat(64),
                "standings": [{
                    "model_id": "model_one",
                    "epoch_rank": 1,
                    "overall_rating": 88.86,
                    "points_awarded": 1000
                }]
            }]
        });
        fixture["roster"][0]["season_points"] = serde_json::json!(1000);
        fixture["roster"][0]["epochs_played"] = serde_json::json!(1);
        fixture["roster"][0]["epoch_wins"] = serde_json::json!(1);
        fixture["roster"][0]["best_epoch_rank"] = serde_json::json!(1);
        fixture["roster"][0]["last_epoch_rank"] = serde_json::json!(1);
        fs::write(&path, fixture.to_string()).expect("write weekly snapshot");

        let response = load_ratings_response(&path);

        assert!(response.active);
        let league = response.league.expect("league should be public");
        assert_eq!(league.week_id, "2026-W30");
        assert_eq!(league.recent_epochs.len(), 1);
        assert_eq!(response.roster[0].season_points, 1000);
        let _ = fs::remove_file(path);
    }

    #[test]
    fn malformed_or_out_of_range_snapshot_is_not_exposed() {
        let malformed_path = temp_snapshot_path("malformed");
        fs::write(&malformed_path, "{not json").expect("write malformed snapshot");
        let malformed = load_ratings_response(&malformed_path);
        assert!(!malformed.active);

        let invalid_path = temp_snapshot_path("invalid-rating");
        let invalid_json = valid_snapshot_json().replace("92.5", "101.0");
        fs::write(&invalid_path, invalid_json).expect("write invalid snapshot");
        let invalid = load_ratings_response(&invalid_path);
        assert!(!invalid.active);
        assert!(invalid.roster.is_empty());

        let _ = fs::remove_file(malformed_path);
        let _ = fs::remove_file(invalid_path);
    }
}
