// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var FlagStatus;
(function (FlagStatus) {
    FlagStatus[FlagStatus["AtBase"] = 0] = "AtBase";
    FlagStatus[FlagStatus["Carried"] = 1] = "Carried";
    FlagStatus[FlagStatus["Dropped"] = 2] = "Dropped";
})(FlagStatus || (FlagStatus = {}));
//# sourceMappingURL=flag-status.js.map