// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from 'flatbuffers';
import { MessagePayload } from '../game-protocol/message-payload.js';
import { MessageType } from '../game-protocol/message-type.js';
export class GameMessage {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsGameMessage(bb, obj) {
        return (obj || new GameMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsGameMessage(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new GameMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static bufferHasIdentifier(bb) {
        return bb.__has_identifier('MGS1');
    }
    msgType() {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readInt8(this.bb_pos + offset) : MessageType.Welcome;
    }
    actualMessageType() {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readUint8(this.bb_pos + offset) : MessagePayload.NONE;
    }
    actualMessage(obj) {
        const offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
    }
    protocolVersion() {
        const offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? this.bb.readUint32(this.bb_pos + offset) : 1;
    }
    static startGameMessage(builder) {
        builder.startObject(4);
    }
    static addMsgType(builder, msgType) {
        builder.addFieldInt8(0, msgType, MessageType.Welcome);
    }
    static addActualMessageType(builder, actualMessageType) {
        builder.addFieldInt8(1, actualMessageType, MessagePayload.NONE);
    }
    static addActualMessage(builder, actualMessageOffset) {
        builder.addFieldOffset(2, actualMessageOffset, 0);
    }
    static addProtocolVersion(builder, protocolVersion) {
        builder.addFieldInt32(3, protocolVersion, 1);
    }
    static endGameMessage(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static finishGameMessageBuffer(builder, offset) {
        builder.finish(offset, 'MGS1');
    }
    static finishSizePrefixedGameMessageBuffer(builder, offset) {
        builder.finish(offset, 'MGS1', true);
    }
    static createGameMessage(builder, msgType, actualMessageType, actualMessageOffset, protocolVersion) {
        GameMessage.startGameMessage(builder);
        GameMessage.addMsgType(builder, msgType);
        GameMessage.addActualMessageType(builder, actualMessageType);
        GameMessage.addActualMessage(builder, actualMessageOffset);
        GameMessage.addProtocolVersion(builder, protocolVersion);
        return GameMessage.endGameMessage(builder);
    }
}
//# sourceMappingURL=game-message.js.map