// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum GameModeType {
  FreeForAll = 0,
  TeamDeathmatch = 1,
  CaptureTheFlag = 2
}
