// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum GameEventType {
  BulletImpact = 0,
  Explosion = 1,
  WeaponFire = 2,
  PlayerDamageEffect = 3,
  WallImpact = 4,
  WallDestroyed = 5,
  PowerupActivated = 6,
  FlagGrabbed = 7,
  FlagDropped = 8,
  FlagReturned = 9,
  FlagCaptured = 10
}
