// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum KillContext {
  Normal = 0,
  Revenge = 1,
  FirstBlood = 2,
  Shutdown = 3,
  LongRange = 4
}
