// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var KillContext;
(function (KillContext) {
    KillContext[KillContext["Normal"] = 0] = "Normal";
    KillContext[KillContext["Revenge"] = 1] = "Revenge";
    KillContext[KillContext["FirstBlood"] = 2] = "FirstBlood";
    KillContext[KillContext["Shutdown"] = 3] = "Shutdown";
    KillContext[KillContext["LongRange"] = 4] = "LongRange";
})(KillContext || (KillContext = {}));
//# sourceMappingURL=kill-context.js.map