// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { GameModeType } from '../game-protocol/game-mode-type.js';
import { MatchStateType } from '../game-protocol/match-state-type.js';
import { TeamScoreEntry } from '../game-protocol/team-score-entry.js';
import { Vec2 } from '../game-protocol/vec2.js';


export class MatchInfo {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MatchInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMatchInfo(bb:flatbuffers.ByteBuffer, obj?:MatchInfo):MatchInfo {
  return (obj || new MatchInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMatchInfo(bb:flatbuffers.ByteBuffer, obj?:MatchInfo):MatchInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MatchInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

timeRemaining():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

matchState():MatchStateType {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : MatchStateType.Waiting;
}

winnerId():string|null
winnerId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
winnerId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

winnerName():string|null
winnerName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
winnerName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

gameMode():GameModeType {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : GameModeType.FreeForAll;
}

teamScores(index: number, obj?:TeamScoreEntry):TeamScoreEntry|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new TeamScoreEntry()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

teamScoresLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

team1CommanderId():string|null
team1CommanderId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
team1CommanderId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

team2CommanderId():string|null
team2CommanderId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
team2CommanderId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

team1CommanderWaypoint(obj?:Vec2):Vec2|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? (obj || new Vec2()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

team2CommanderWaypoint(obj?:Vec2):Vec2|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new Vec2()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

team1CommanderAttackBias():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

team2CommanderAttackBias():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startMatchInfo(builder:flatbuffers.Builder) {
  builder.startObject(12);
}

static addTimeRemaining(builder:flatbuffers.Builder, timeRemaining:number) {
  builder.addFieldFloat32(0, timeRemaining, 0.0);
}

static addMatchState(builder:flatbuffers.Builder, matchState:MatchStateType) {
  builder.addFieldInt8(1, matchState, MatchStateType.Waiting);
}

static addWinnerId(builder:flatbuffers.Builder, winnerIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, winnerIdOffset, 0);
}

static addWinnerName(builder:flatbuffers.Builder, winnerNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, winnerNameOffset, 0);
}

static addGameMode(builder:flatbuffers.Builder, gameMode:GameModeType) {
  builder.addFieldInt8(4, gameMode, GameModeType.FreeForAll);
}

static addTeamScores(builder:flatbuffers.Builder, teamScoresOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, teamScoresOffset, 0);
}

static createTeamScoresVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTeamScoresVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addTeam1CommanderId(builder:flatbuffers.Builder, team1CommanderIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, team1CommanderIdOffset, 0);
}

static addTeam2CommanderId(builder:flatbuffers.Builder, team2CommanderIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, team2CommanderIdOffset, 0);
}

static addTeam1CommanderWaypoint(builder:flatbuffers.Builder, team1CommanderWaypointOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, team1CommanderWaypointOffset, 0);
}

static addTeam2CommanderWaypoint(builder:flatbuffers.Builder, team2CommanderWaypointOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, team2CommanderWaypointOffset, 0);
}

static addTeam1CommanderAttackBias(builder:flatbuffers.Builder, team1CommanderAttackBias:number) {
  builder.addFieldFloat32(10, team1CommanderAttackBias, 0.0);
}

static addTeam2CommanderAttackBias(builder:flatbuffers.Builder, team2CommanderAttackBias:number) {
  builder.addFieldFloat32(11, team2CommanderAttackBias, 0.0);
}

static endMatchInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
