// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var MessageType;
(function (MessageType) {
    MessageType[MessageType["Welcome"] = 0] = "Welcome";
    MessageType[MessageType["InitialState"] = 1] = "InitialState";
    MessageType[MessageType["DeltaState"] = 2] = "DeltaState";
    MessageType[MessageType["Input"] = 3] = "Input";
    MessageType[MessageType["Chat"] = 4] = "Chat";
    MessageType[MessageType["MatchUpdate"] = 5] = "MatchUpdate";
})(MessageType || (MessageType = {}));
//# sourceMappingURL=message-type.js.map