// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum MessageType {
  Welcome = 0,
  InitialState = 1,
  DeltaState = 2,
  Input = 3,
  Chat = 4,
  MatchUpdate = 5
}
