// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { ChatMessage } from '../game-protocol/chat-message.js';
import { DeltaStateMessage } from '../game-protocol/delta-state-message.js';
import { InitialStateMessage } from '../game-protocol/initial-state-message.js';
import { MatchInfo } from '../game-protocol/match-info.js';
import { PlayerInput } from '../game-protocol/player-input.js';
import { WelcomeMessage } from '../game-protocol/welcome-message.js';


export enum MessagePayload {
  NONE = 0,
  WelcomeMessage = 1,
  InitialStateMessage = 2,
  DeltaStateMessage = 3,
  PlayerInput = 4,
  ChatMessage = 5,
  MatchInfo = 6
}

export function unionToMessagePayload(
  type: MessagePayload,
  accessor: (obj:ChatMessage|DeltaStateMessage|InitialStateMessage|MatchInfo|PlayerInput|WelcomeMessage) => ChatMessage|DeltaStateMessage|InitialStateMessage|MatchInfo|PlayerInput|WelcomeMessage|null
): ChatMessage|DeltaStateMessage|InitialStateMessage|MatchInfo|PlayerInput|WelcomeMessage|null {
  switch(MessagePayload[type]) {
    case 'NONE': return null; 
    case 'WelcomeMessage': return accessor(new WelcomeMessage())! as WelcomeMessage;
    case 'InitialStateMessage': return accessor(new InitialStateMessage())! as InitialStateMessage;
    case 'DeltaStateMessage': return accessor(new DeltaStateMessage())! as DeltaStateMessage;
    case 'PlayerInput': return accessor(new PlayerInput())! as PlayerInput;
    case 'ChatMessage': return accessor(new ChatMessage())! as ChatMessage;
    case 'MatchInfo': return accessor(new MatchInfo())! as MatchInfo;
    default: return null;
  }
}

export function unionListToMessagePayload(
  type: MessagePayload, 
  accessor: (index: number, obj:ChatMessage|DeltaStateMessage|InitialStateMessage|MatchInfo|PlayerInput|WelcomeMessage) => ChatMessage|DeltaStateMessage|InitialStateMessage|MatchInfo|PlayerInput|WelcomeMessage|null, 
  index: number
): ChatMessage|DeltaStateMessage|InitialStateMessage|MatchInfo|PlayerInput|WelcomeMessage|null {
  switch(MessagePayload[type]) {
    case 'NONE': return null; 
    case 'WelcomeMessage': return accessor(index, new WelcomeMessage())! as WelcomeMessage;
    case 'InitialStateMessage': return accessor(index, new InitialStateMessage())! as InitialStateMessage;
    case 'DeltaStateMessage': return accessor(index, new DeltaStateMessage())! as DeltaStateMessage;
    case 'PlayerInput': return accessor(index, new PlayerInput())! as PlayerInput;
    case 'ChatMessage': return accessor(index, new ChatMessage())! as ChatMessage;
    case 'MatchInfo': return accessor(index, new MatchInfo())! as MatchInfo;
    default: return null;
  }
}
