// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var PickupType;
(function (PickupType) {
    PickupType[PickupType["Health"] = 0] = "Health";
    PickupType[PickupType["Ammo"] = 1] = "Ammo";
    PickupType[PickupType["WeaponCrate"] = 2] = "WeaponCrate";
    PickupType[PickupType["SpeedBoost"] = 3] = "SpeedBoost";
    PickupType[PickupType["DamageBoost"] = 4] = "DamageBoost";
    PickupType[PickupType["Shield"] = 5] = "Shield";
    PickupType[PickupType["FlagRed"] = 6] = "FlagRed";
    PickupType[PickupType["FlagBlue"] = 7] = "FlagBlue";
})(PickupType || (PickupType = {}));
//# sourceMappingURL=pickup-type.js.map