// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PickupType } from '../game-protocol/pickup-type.js';
import { WeaponType } from '../game-protocol/weapon-type.js';


export class Pickup {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Pickup {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPickup(bb:flatbuffers.ByteBuffer, obj?:Pickup):Pickup {
  return (obj || new Pickup()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPickup(bb:flatbuffers.ByteBuffer, obj?:Pickup):Pickup {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Pickup()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

x():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

y():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

pickupType():PickupType {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : PickupType.Health;
}

weaponType():WeaponType {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : WeaponType.Pistol;
}

isActive():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startPickup(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addX(builder:flatbuffers.Builder, x:number) {
  builder.addFieldFloat32(1, x, 0.0);
}

static addY(builder:flatbuffers.Builder, y:number) {
  builder.addFieldFloat32(2, y, 0.0);
}

static addPickupType(builder:flatbuffers.Builder, pickupType:PickupType) {
  builder.addFieldInt8(3, pickupType, PickupType.Health);
}

static addWeaponType(builder:flatbuffers.Builder, weaponType:WeaponType) {
  builder.addFieldInt8(4, weaponType, WeaponType.Pistol);
}

static addIsActive(builder:flatbuffers.Builder, isActive:boolean) {
  builder.addFieldInt8(5, +isActive, +false);
}

static endPickup(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPickup(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, x:number, y:number, pickupType:PickupType, weaponType:WeaponType, isActive:boolean):flatbuffers.Offset {
  Pickup.startPickup(builder);
  Pickup.addId(builder, idOffset);
  Pickup.addX(builder, x);
  Pickup.addY(builder, y);
  Pickup.addPickupType(builder, pickupType);
  Pickup.addWeaponType(builder, weaponType);
  Pickup.addIsActive(builder, isActive);
  return Pickup.endPickup(builder);
}
}
