// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum PickupType {
  Health = 0,
  Ammo = 1,
  WeaponCrate = 2,
  SpeedBoost = 3,
  DamageBoost = 4,
  Shield = 5,
  FlagRed = 6,
  FlagBlue = 7
}
