// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from 'https://cdn.jsdelivr.net/npm/flatbuffers@23.5.26/+esm';
import { WeaponType } from '../game-protocol/weapon-type.js';
export class ProjectileState {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsProjectileState(bb, obj) {
        return (obj || new ProjectileState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsProjectileState(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new ProjectileState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    id(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    x() {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
    }
    y() {
        const offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
    }
    ownerId(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    weaponType() {
        const offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? this.bb.readInt8(this.bb_pos + offset) : WeaponType.Pistol;
    }
    velocityX() {
        const offset = this.bb.__offset(this.bb_pos, 14);
        return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
    }
    velocityY() {
        const offset = this.bb.__offset(this.bb_pos, 16);
        return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
    }
    static startProjectileState(builder) {
        builder.startObject(7);
    }
    static addId(builder, idOffset) {
        builder.addFieldOffset(0, idOffset, 0);
    }
    static addX(builder, x) {
        builder.addFieldFloat32(1, x, 0.0);
    }
    static addY(builder, y) {
        builder.addFieldFloat32(2, y, 0.0);
    }
    static addOwnerId(builder, ownerIdOffset) {
        builder.addFieldOffset(3, ownerIdOffset, 0);
    }
    static addWeaponType(builder, weaponType) {
        builder.addFieldInt8(4, weaponType, WeaponType.Pistol);
    }
    static addVelocityX(builder, velocityX) {
        builder.addFieldFloat32(5, velocityX, 0.0);
    }
    static addVelocityY(builder, velocityY) {
        builder.addFieldFloat32(6, velocityY, 0.0);
    }
    static endProjectileState(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static createProjectileState(builder, idOffset, x, y, ownerIdOffset, weaponType, velocityX, velocityY) {
        ProjectileState.startProjectileState(builder);
        ProjectileState.addId(builder, idOffset);
        ProjectileState.addX(builder, x);
        ProjectileState.addY(builder, y);
        ProjectileState.addOwnerId(builder, ownerIdOffset);
        ProjectileState.addWeaponType(builder, weaponType);
        ProjectileState.addVelocityX(builder, velocityX);
        ProjectileState.addVelocityY(builder, velocityY);
        return ProjectileState.endProjectileState(builder);
    }
}
//# sourceMappingURL=projectile-state.js.map
