// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum SurfaceType {
  Concrete = 0,
  Metal = 1,
  Wood = 2,
  Glass = 3
}
