// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var SurfaceType;
(function (SurfaceType) {
    SurfaceType[SurfaceType["Concrete"] = 0] = "Concrete";
    SurfaceType[SurfaceType["Metal"] = 1] = "Metal";
    SurfaceType[SurfaceType["Wood"] = 2] = "Wood";
    SurfaceType[SurfaceType["Glass"] = 3] = "Glass";
})(SurfaceType || (SurfaceType = {}));
//# sourceMappingURL=surface-type.js.map