// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var Team;
(function (Team) {
    Team[Team["Spectator"] = 0] = "Spectator";
    Team[Team["Team1"] = 1] = "Team1";
    Team[Team["Team2"] = 2] = "Team2";
})(Team || (Team = {}));
//# sourceMappingURL=team.js.map