// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var WeaponType;
(function (WeaponType) {
    WeaponType[WeaponType["Pistol"] = 0] = "Pistol";
    WeaponType[WeaponType["Shotgun"] = 1] = "Shotgun";
    WeaponType[WeaponType["Rifle"] = 2] = "Rifle";
    WeaponType[WeaponType["Sniper"] = 3] = "Sniper";
    WeaponType[WeaponType["Melee"] = 4] = "Melee";
})(WeaponType || (WeaponType = {}));
//# sourceMappingURL=weapon-type.js.map