// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum WeaponType {
  Pistol = 0,
  Shotgun = 1,
  Rifle = 2,
  Sniper = 3,
  Melee = 4
}
