// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ZoneType } from '../game-protocol/zone-type.js';


export class Zone {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Zone {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsZone(bb:flatbuffers.ByteBuffer, obj?:Zone):Zone {
  return (obj || new Zone()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsZone(bb:flatbuffers.ByteBuffer, obj?:Zone):Zone {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Zone()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

x():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

y():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

width():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

height():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

zoneType():ZoneType {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ZoneType.SlowZone;
}

direction():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startZone(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addX(builder:flatbuffers.Builder, x:number) {
  builder.addFieldFloat32(1, x, 0.0);
}

static addY(builder:flatbuffers.Builder, y:number) {
  builder.addFieldFloat32(2, y, 0.0);
}

static addWidth(builder:flatbuffers.Builder, width:number) {
  builder.addFieldFloat32(3, width, 0.0);
}

static addHeight(builder:flatbuffers.Builder, height:number) {
  builder.addFieldFloat32(4, height, 0.0);
}

static addZoneType(builder:flatbuffers.Builder, zoneType:ZoneType) {
  builder.addFieldInt8(5, zoneType, ZoneType.SlowZone);
}

static addDirection(builder:flatbuffers.Builder, direction:number) {
  builder.addFieldFloat32(6, direction, 0.0);
}

static endZone(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createZone(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, x:number, y:number, width:number, height:number, zoneType:ZoneType, direction:number):flatbuffers.Offset {
  Zone.startZone(builder);
  Zone.addId(builder, idOffset);
  Zone.addX(builder, x);
  Zone.addY(builder, y);
  Zone.addWidth(builder, width);
  Zone.addHeight(builder, height);
  Zone.addZoneType(builder, zoneType);
  Zone.addDirection(builder, direction);
  return Zone.endZone(builder);
}
}
