// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var ZoneType;
(function (ZoneType) {
    ZoneType[ZoneType["SlowZone"] = 0] = "SlowZone";
    ZoneType[ZoneType["DamageZone"] = 1] = "DamageZone";
    ZoneType[ZoneType["BoostPad"] = 2] = "BoostPad";
})(ZoneType || (ZoneType = {}));
//# sourceMappingURL=zone-type.js.map