// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from 'flatbuffers';
import { ZoneType } from '../game-protocol/zone-type.js';
export class Zone {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsZone(bb, obj) {
        return (obj || new Zone()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsZone(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new Zone()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    id(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    x() {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
    }
    y() {
        const offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
    }
    width() {
        const offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
    }
    height() {
        const offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
    }
    zoneType() {
        const offset = this.bb.__offset(this.bb_pos, 14);
        return offset ? this.bb.readInt8(this.bb_pos + offset) : ZoneType.SlowZone;
    }
    direction() {
        const offset = this.bb.__offset(this.bb_pos, 16);
        return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
    }
    static startZone(builder) {
        builder.startObject(7);
    }
    static addId(builder, idOffset) {
        builder.addFieldOffset(0, idOffset, 0);
    }
    static addX(builder, x) {
        builder.addFieldFloat32(1, x, 0.0);
    }
    static addY(builder, y) {
        builder.addFieldFloat32(2, y, 0.0);
    }
    static addWidth(builder, width) {
        builder.addFieldFloat32(3, width, 0.0);
    }
    static addHeight(builder, height) {
        builder.addFieldFloat32(4, height, 0.0);
    }
    static addZoneType(builder, zoneType) {
        builder.addFieldInt8(5, zoneType, ZoneType.SlowZone);
    }
    static addDirection(builder, direction) {
        builder.addFieldFloat32(6, direction, 0.0);
    }
    static endZone(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static createZone(builder, idOffset, x, y, width, height, zoneType, direction) {
        Zone.startZone(builder);
        Zone.addId(builder, idOffset);
        Zone.addX(builder, x);
        Zone.addY(builder, y);
        Zone.addWidth(builder, width);
        Zone.addHeight(builder, height);
        Zone.addZoneType(builder, zoneType);
        Zone.addDirection(builder, direction);
        return Zone.endZone(builder);
    }
}
//# sourceMappingURL=zone.js.map